import { Organization, Template } from '@sdk';
/**
 * Creates a Template object with all required fields, filling in defaults for any undefined values
 * @param partial - Partial template data (all fields optional)
 * @returns Complete Template object with defaults
 */
export function SimpleTemplate(partial?: Partial<Template>): Template {
	const defaultOrg: Organization = {
		__typename: 'Organization',
		actions: [],
		activatedTriggers: [],
		createdAt: undefined,
		createdTags: [],
		deletedAt: undefined,
		domain: undefined,
		featurePreviewSettings: undefined,
		forms: [],
		id: undefined,
		installedPacks: [],
		isDeleted: undefined,
		isEnabled: undefined,
		isInternal: undefined,
		isMsp: undefined,
		isOnboarding: undefined,
		isStaff: undefined,
		managedAndSubOrgs: [],
		managedOrgAutoInstallingWorkflows: [],
		managedOrgs: [],
		managingOrg: undefined,
		managingOrgId: undefined,
		name: '',
		orgSlug: undefined,
		packConfigs: [],
		resultsRetentionDays: undefined,
		rocSiteId: undefined,
		supportAccessStatus: undefined,
		tags: [],
		templates: [],
		tid: undefined,
		triggerInstances: [],
		triggers: [],
		users: [],
		variables: [],
		visibleActions: [],
		visiblePackConfigs: [],
		visibleWorkflows: [],
		workflowExecutions: [],
		workflows: [],
	};

	return {
		__typename: 'Template',
		body: partial?.body ?? '',
		cloneOverrides: partial?.cloneOverrides ?? undefined,
		clonedFrom: partial?.clonedFrom ?? undefined,
		clonedFromId: partial?.clonedFromId ?? undefined,
		clones: partial?.clones ?? undefined,
		contentType: partial?.contentType ?? '',
		context: partial?.context ?? undefined,
		createdAt: partial?.createdAt ?? '',
		description: partial?.description ?? undefined,
		id: partial?.id ?? '',
		isShared: partial?.isShared ?? undefined,
		isSynchronized: partial?.isSynchronized ?? undefined,
		language: partial?.language ?? '',
		name: partial?.name ?? '',
		orgId: partial?.orgId ?? '',
		organization: partial?.organization ?? defaultOrg,
		permission: partial?.permission ?? undefined,
		tags: partial?.tags ?? [],
		unpackedFrom: partial?.unpackedFrom ?? undefined,
		unpackedFromId: partial?.unpackedFromId ?? undefined,
		updatedAt: partial?.updatedAt ?? '',
		updatedBy: partial?.updatedBy ?? undefined,
		updatedById: partial?.updatedById ?? undefined,
	};
}
